### ISSUE TITLE
RedBot Error

### ISSUE THREAD

**Issue by wcollins436** [mnot/redbot#200] opened 2017-10-22 02:13 UTC
I have been using RedBot for a few years and it has been very helpful.
I recently changed my hosting company and now I get the following error
Connection error (Name or service not known)
The URL is
http://www.suspenders-online.com
Would you please tell me what it is that RedBot doesn't like so that I can have the hosting company fix the problem?

Thank you,

Walter
wcollins@suspendedanimation.net

**Comment by mnot** [comment] 2017-10-23 03:15
Duplicate of #199.

**Closed by mnot** 2017-10-23 03:15 UTC
